[package]
name = "advent"
version = "0.1.0"
authors = ["Rasmus Larsen <doctorherbstein@gmail.com>"]
edition = "2018"

[profile.bench]
lto = "thin"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
petgraph = "0.5.1"
regex = "1.4.2"
